### PR TITLE
Added tabular output

### PR DESCRIPTION
**Pull request by gusampaio**
- Added tabluar output using [tabwriter](https://pkg.go.dev/text/tabwriter), which is the package in the standard library for this type of job.
- Also updated the `for` loop to the [range](https://gobyexample.com/range) one, which is the most used way to iterate with slices in go
- Added cli parameter in order to list coins,  e.g.: `go run .\main.go --list=50`, with default of 20

### CODE REVIEW

**Comment by gusampaio** [comment]
#6

**Comment by gusampaio** [comment]
#3

**Comment by gusampaio** [comment]
Added the [flag](https://gobyexample.com/command-line-flags) package in order to iterate with the input parameters

**Review by tavaresrodrigo — APPROVED** [review]
LGTM, I liked the way you approached the range|for, it's clear and seems to be the perfect case for the tabular output.

**Pull request merged**
